### ISSUE TITLE
Make function player look at camera

### ISSUE THREAD

**Issue by Sirmadeira** [Sirmadeira/psycho_project#15]
1.  As camera rotate player spine needs to rotate to slightly look at camera.
2. Do it

**Comment by harryberg1n** [comment]
what were the bones you mentioned for character rotation.

**Comment by Sirmadeira** [comment]
They are sub child of predicted players

**Comment by Sirmadeira** [comment]
Jeez louis bro this was more comple than i expected gonna do it myself
